version: "2"
services:
    # Database service. It's PostgreSQL, see the
    # Dockerfile in ./database
    database:
        build: ./database/
        environment:
            # Custom PGDATA per recommendations from official Docker page
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./postgres-data:/var/lib/postgresql/data/pgdata
    # Web service runs Node
    web:
        # Configuration variables for the app.
        environment:
            - COINPLAN_SERVER_PORT=3000
            - COINPLAN_DB_USER=coinplan
            - COINPLAN_DB_DATABASE=coinplan
            - COINPLAN_DB_TEST_DATABASE=coinplan_testing
            - COINPLAN_DB_PASSWORD=
            - COINPLAN_DB_HOST=database # Docker will set this hostname
            - COINPLAN_DB_PORT=5432
            - COINPLAN_TOKEN_SECRET=?
            - COINPLAN_LOG_FILE=log.txt
        # Set the correct build environment.
        build: ./
        # Link to the database so the app can persist data
        links:
            - database
        # Load the source code into the container.
        # Using a volume allows autorebuild to work.
        volumes:
            - ./:/usr/src/app
        # Map the default port.
        ports:
            - "3000:3000"
              # For production you might want something like:
              # - "80:3000"
        # Don't bring this up without the DB
        depends_on:
            - database
        # Lets docker-compose up work right
        command: ["npm", "start"]